version: "3.4"

services:  # define the services
  flask-api:  # service name
    container_name: flask-api  # container name
    build:  # build the image
      args:  # arguments for Dockerfile's "if" condition
        - FLASK_ENV=dev
      context: .  # means the current directory
    volumes:  # mount the volumes
      - ./src:/src  # mount the src directory to the container
    ports:  # expose the ports
      - 8000:8000  # host_port:container_port
    depends_on:  # depend on the services
      - mongodb  # service name (below)
    networks:  # connect to the networks
      - flask_net  # network name (below)
    environment:
      - MONGO_URL=mongodb://mongodb:27017  # mongodb://service-name:port
      - FLASK_ENV=dev
    restart: always  # restart the container if it stops
  
  mongodb:  # service name (used at "depends_on"; line 14)
    image: mongo:5.0.7  # pull the image from Docker Hub
    container_name: mongo_db  # container name
    restart: always  # restart the container if it stops
    ports:
      - 27017:27017  # host_port:container_port
    networks:
      - flask_net  # network name

networks:  # define the networks
  flask_net:  # network name (used at "networks"; line 16, 29)
    driver: bridge  # bridge network
